gavin:
    build: .
    #command: python /usr/local/bin/ipython notebook --no-browser --port 8888 --debug --ip=0.0.0.0 --notebook-dir=/notebook-dir
    ports:
        - "8888"
    volumes:
        - /vagrant/notebooks:/notebook-dir/shared
    environment:
        VIRTUAL_HOST: gavin.ipython.com
        VIRTUAL_PORT: 8888

beth:
    build: .
    #command: python /usr/local/bin/ipython notebook --no-browser --port 8888 --debug --ip=0.0.0.0 --notebook-dir=/notebook-dir
    ports:
        - "8888"
    volumes:
        - /vagrant/notebooks:/notebook-dir/shared
    environment:
        VIRTUAL_HOST: beth.ipython.com
        VIRTUAL_PORT: 8888
